apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: logistics-api
  namespace: logistics
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: logistics-api
